// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package databasekafkaconfig

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-digitalocean.databaseKafkaConfig.DatabaseKafkaConfig",
		reflect.TypeOf((*DatabaseKafkaConfig)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "autoCreateTopicsEnable", GoGetter: "AutoCreateTopicsEnable"},
			_jsii_.MemberProperty{JsiiProperty: "autoCreateTopicsEnableInput", GoGetter: "AutoCreateTopicsEnableInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "clusterId", GoGetter: "ClusterId"},
			_jsii_.MemberProperty{JsiiProperty: "clusterIdInput", GoGetter: "ClusterIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "groupInitialRebalanceDelayMs", GoGetter: "GroupInitialRebalanceDelayMs"},
			_jsii_.MemberProperty{JsiiProperty: "groupInitialRebalanceDelayMsInput", GoGetter: "GroupInitialRebalanceDelayMsInput"},
			_jsii_.MemberProperty{JsiiProperty: "groupMaxSessionTimeoutMs", GoGetter: "GroupMaxSessionTimeoutMs"},
			_jsii_.MemberProperty{JsiiProperty: "groupMaxSessionTimeoutMsInput", GoGetter: "GroupMaxSessionTimeoutMsInput"},
			_jsii_.MemberProperty{JsiiProperty: "groupMinSessionTimeoutMs", GoGetter: "GroupMinSessionTimeoutMs"},
			_jsii_.MemberProperty{JsiiProperty: "groupMinSessionTimeoutMsInput", GoGetter: "GroupMinSessionTimeoutMsInput"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "logCleanerDeleteRetentionMs", GoGetter: "LogCleanerDeleteRetentionMs"},
			_jsii_.MemberProperty{JsiiProperty: "logCleanerDeleteRetentionMsInput", GoGetter: "LogCleanerDeleteRetentionMsInput"},
			_jsii_.MemberProperty{JsiiProperty: "logCleanerMinCompactionLagMs", GoGetter: "LogCleanerMinCompactionLagMs"},
			_jsii_.MemberProperty{JsiiProperty: "logCleanerMinCompactionLagMsInput", GoGetter: "LogCleanerMinCompactionLagMsInput"},
			_jsii_.MemberProperty{JsiiProperty: "logFlushIntervalMs", GoGetter: "LogFlushIntervalMs"},
			_jsii_.MemberProperty{JsiiProperty: "logFlushIntervalMsInput", GoGetter: "LogFlushIntervalMsInput"},
			_jsii_.MemberProperty{JsiiProperty: "logIndexIntervalBytes", GoGetter: "LogIndexIntervalBytes"},
			_jsii_.MemberProperty{JsiiProperty: "logIndexIntervalBytesInput", GoGetter: "LogIndexIntervalBytesInput"},
			_jsii_.MemberProperty{JsiiProperty: "logMessageDownconversionEnable", GoGetter: "LogMessageDownconversionEnable"},
			_jsii_.MemberProperty{JsiiProperty: "logMessageDownconversionEnableInput", GoGetter: "LogMessageDownconversionEnableInput"},
			_jsii_.MemberProperty{JsiiProperty: "logMessageTimestampDifferenceMaxMs", GoGetter: "LogMessageTimestampDifferenceMaxMs"},
			_jsii_.MemberProperty{JsiiProperty: "logMessageTimestampDifferenceMaxMsInput", GoGetter: "LogMessageTimestampDifferenceMaxMsInput"},
			_jsii_.MemberProperty{JsiiProperty: "logPreallocate", GoGetter: "LogPreallocate"},
			_jsii_.MemberProperty{JsiiProperty: "logPreallocateInput", GoGetter: "LogPreallocateInput"},
			_jsii_.MemberProperty{JsiiProperty: "logRetentionBytes", GoGetter: "LogRetentionBytes"},
			_jsii_.MemberProperty{JsiiProperty: "logRetentionBytesInput", GoGetter: "LogRetentionBytesInput"},
			_jsii_.MemberProperty{JsiiProperty: "logRetentionHours", GoGetter: "LogRetentionHours"},
			_jsii_.MemberProperty{JsiiProperty: "logRetentionHoursInput", GoGetter: "LogRetentionHoursInput"},
			_jsii_.MemberProperty{JsiiProperty: "logRetentionMs", GoGetter: "LogRetentionMs"},
			_jsii_.MemberProperty{JsiiProperty: "logRetentionMsInput", GoGetter: "LogRetentionMsInput"},
			_jsii_.MemberProperty{JsiiProperty: "logRollJitterMs", GoGetter: "LogRollJitterMs"},
			_jsii_.MemberProperty{JsiiProperty: "logRollJitterMsInput", GoGetter: "LogRollJitterMsInput"},
			_jsii_.MemberProperty{JsiiProperty: "logSegmentDeleteDelayMs", GoGetter: "LogSegmentDeleteDelayMs"},
			_jsii_.MemberProperty{JsiiProperty: "logSegmentDeleteDelayMsInput", GoGetter: "LogSegmentDeleteDelayMsInput"},
			_jsii_.MemberProperty{JsiiProperty: "messageMaxBytes", GoGetter: "MessageMaxBytes"},
			_jsii_.MemberProperty{JsiiProperty: "messageMaxBytesInput", GoGetter: "MessageMaxBytesInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutoCreateTopicsEnable", GoMethod: "ResetAutoCreateTopicsEnable"},
			_jsii_.MemberMethod{JsiiMethod: "resetGroupInitialRebalanceDelayMs", GoMethod: "ResetGroupInitialRebalanceDelayMs"},
			_jsii_.MemberMethod{JsiiMethod: "resetGroupMaxSessionTimeoutMs", GoMethod: "ResetGroupMaxSessionTimeoutMs"},
			_jsii_.MemberMethod{JsiiMethod: "resetGroupMinSessionTimeoutMs", GoMethod: "ResetGroupMinSessionTimeoutMs"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogCleanerDeleteRetentionMs", GoMethod: "ResetLogCleanerDeleteRetentionMs"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogCleanerMinCompactionLagMs", GoMethod: "ResetLogCleanerMinCompactionLagMs"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogFlushIntervalMs", GoMethod: "ResetLogFlushIntervalMs"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogIndexIntervalBytes", GoMethod: "ResetLogIndexIntervalBytes"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogMessageDownconversionEnable", GoMethod: "ResetLogMessageDownconversionEnable"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogMessageTimestampDifferenceMaxMs", GoMethod: "ResetLogMessageTimestampDifferenceMaxMs"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogPreallocate", GoMethod: "ResetLogPreallocate"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogRetentionBytes", GoMethod: "ResetLogRetentionBytes"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogRetentionHours", GoMethod: "ResetLogRetentionHours"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogRetentionMs", GoMethod: "ResetLogRetentionMs"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogRollJitterMs", GoMethod: "ResetLogRollJitterMs"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogSegmentDeleteDelayMs", GoMethod: "ResetLogSegmentDeleteDelayMs"},
			_jsii_.MemberMethod{JsiiMethod: "resetMessageMaxBytes", GoMethod: "ResetMessageMaxBytes"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
		},
		func() interface{} {
			j := jsiiProxy_DatabaseKafkaConfig{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-digitalocean.databaseKafkaConfig.DatabaseKafkaConfigConfig",
		reflect.TypeOf((*DatabaseKafkaConfigConfig)(nil)).Elem(),
	)
}
