// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package databasekafkatopic

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-digitalocean.databaseKafkaTopic.DatabaseKafkaTopic",
		reflect.TypeOf((*DatabaseKafkaTopic)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "clusterId", GoGetter: "ClusterId"},
			_jsii_.MemberProperty{JsiiProperty: "clusterIdInput", GoGetter: "ClusterIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "config", GoGetter: "Config"},
			_jsii_.MemberProperty{JsiiProperty: "configInput", GoGetter: "ConfigInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "partitionCount", GoGetter: "PartitionCount"},
			_jsii_.MemberProperty{JsiiProperty: "partitionCountInput", GoGetter: "PartitionCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putConfig", GoMethod: "PutConfig"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "replicationFactor", GoGetter: "ReplicationFactor"},
			_jsii_.MemberProperty{JsiiProperty: "replicationFactorInput", GoGetter: "ReplicationFactorInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetConfig", GoMethod: "ResetConfig"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetPartitionCount", GoMethod: "ResetPartitionCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetReplicationFactor", GoMethod: "ResetReplicationFactor"},
			_jsii_.MemberProperty{JsiiProperty: "state", GoGetter: "State"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
		},
		func() interface{} {
			j := jsiiProxy_DatabaseKafkaTopic{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-digitalocean.databaseKafkaTopic.DatabaseKafkaTopicConfig",
		reflect.TypeOf((*DatabaseKafkaTopicConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-digitalocean.databaseKafkaTopic.DatabaseKafkaTopicConfigA",
		reflect.TypeOf((*DatabaseKafkaTopicConfigA)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-digitalocean.databaseKafkaTopic.DatabaseKafkaTopicConfigAList",
		reflect.TypeOf((*DatabaseKafkaTopicConfigAList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_DatabaseKafkaTopicConfigAList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-digitalocean.databaseKafkaTopic.DatabaseKafkaTopicConfigAOutputReference",
		reflect.TypeOf((*DatabaseKafkaTopicConfigAOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "cleanupPolicy", GoGetter: "CleanupPolicy"},
			_jsii_.MemberProperty{JsiiProperty: "cleanupPolicyInput", GoGetter: "CleanupPolicyInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberProperty{JsiiProperty: "compressionType", GoGetter: "CompressionType"},
			_jsii_.MemberProperty{JsiiProperty: "compressionTypeInput", GoGetter: "CompressionTypeInput"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "deleteRetentionMs", GoGetter: "DeleteRetentionMs"},
			_jsii_.MemberProperty{JsiiProperty: "deleteRetentionMsInput", GoGetter: "DeleteRetentionMsInput"},
			_jsii_.MemberProperty{JsiiProperty: "fileDeleteDelayMs", GoGetter: "FileDeleteDelayMs"},
			_jsii_.MemberProperty{JsiiProperty: "fileDeleteDelayMsInput", GoGetter: "FileDeleteDelayMsInput"},
			_jsii_.MemberProperty{JsiiProperty: "flushMessages", GoGetter: "FlushMessages"},
			_jsii_.MemberProperty{JsiiProperty: "flushMessagesInput", GoGetter: "FlushMessagesInput"},
			_jsii_.MemberProperty{JsiiProperty: "flushMs", GoGetter: "FlushMs"},
			_jsii_.MemberProperty{JsiiProperty: "flushMsInput", GoGetter: "FlushMsInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "indexIntervalBytes", GoGetter: "IndexIntervalBytes"},
			_jsii_.MemberProperty{JsiiProperty: "indexIntervalBytesInput", GoGetter: "IndexIntervalBytesInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "maxCompactionLagMs", GoGetter: "MaxCompactionLagMs"},
			_jsii_.MemberProperty{JsiiProperty: "maxCompactionLagMsInput", GoGetter: "MaxCompactionLagMsInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxMessageBytes", GoGetter: "MaxMessageBytes"},
			_jsii_.MemberProperty{JsiiProperty: "maxMessageBytesInput", GoGetter: "MaxMessageBytesInput"},
			_jsii_.MemberProperty{JsiiProperty: "messageDownConversionEnable", GoGetter: "MessageDownConversionEnable"},
			_jsii_.MemberProperty{JsiiProperty: "messageDownConversionEnableInput", GoGetter: "MessageDownConversionEnableInput"},
			_jsii_.MemberProperty{JsiiProperty: "messageFormatVersion", GoGetter: "MessageFormatVersion"},
			_jsii_.MemberProperty{JsiiProperty: "messageFormatVersionInput", GoGetter: "MessageFormatVersionInput"},
			_jsii_.MemberProperty{JsiiProperty: "messageTimestampDifferenceMaxMs", GoGetter: "MessageTimestampDifferenceMaxMs"},
			_jsii_.MemberProperty{JsiiProperty: "messageTimestampDifferenceMaxMsInput", GoGetter: "MessageTimestampDifferenceMaxMsInput"},
			_jsii_.MemberProperty{JsiiProperty: "messageTimestampType", GoGetter: "MessageTimestampType"},
			_jsii_.MemberProperty{JsiiProperty: "messageTimestampTypeInput", GoGetter: "MessageTimestampTypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "minCleanableDirtyRatio", GoGetter: "MinCleanableDirtyRatio"},
			_jsii_.MemberProperty{JsiiProperty: "minCleanableDirtyRatioInput", GoGetter: "MinCleanableDirtyRatioInput"},
			_jsii_.MemberProperty{JsiiProperty: "minCompactionLagMs", GoGetter: "MinCompactionLagMs"},
			_jsii_.MemberProperty{JsiiProperty: "minCompactionLagMsInput", GoGetter: "MinCompactionLagMsInput"},
			_jsii_.MemberProperty{JsiiProperty: "minInsyncReplicas", GoGetter: "MinInsyncReplicas"},
			_jsii_.MemberProperty{JsiiProperty: "minInsyncReplicasInput", GoGetter: "MinInsyncReplicasInput"},
			_jsii_.MemberProperty{JsiiProperty: "preallocate", GoGetter: "Preallocate"},
			_jsii_.MemberProperty{JsiiProperty: "preallocateInput", GoGetter: "PreallocateInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetCleanupPolicy", GoMethod: "ResetCleanupPolicy"},
			_jsii_.MemberMethod{JsiiMethod: "resetCompressionType", GoMethod: "ResetCompressionType"},
			_jsii_.MemberMethod{JsiiMethod: "resetDeleteRetentionMs", GoMethod: "ResetDeleteRetentionMs"},
			_jsii_.MemberMethod{JsiiMethod: "resetFileDeleteDelayMs", GoMethod: "ResetFileDeleteDelayMs"},
			_jsii_.MemberMethod{JsiiMethod: "resetFlushMessages", GoMethod: "ResetFlushMessages"},
			_jsii_.MemberMethod{JsiiMethod: "resetFlushMs", GoMethod: "ResetFlushMs"},
			_jsii_.MemberMethod{JsiiMethod: "resetIndexIntervalBytes", GoMethod: "ResetIndexIntervalBytes"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxCompactionLagMs", GoMethod: "ResetMaxCompactionLagMs"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxMessageBytes", GoMethod: "ResetMaxMessageBytes"},
			_jsii_.MemberMethod{JsiiMethod: "resetMessageDownConversionEnable", GoMethod: "ResetMessageDownConversionEnable"},
			_jsii_.MemberMethod{JsiiMethod: "resetMessageFormatVersion", GoMethod: "ResetMessageFormatVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetMessageTimestampDifferenceMaxMs", GoMethod: "ResetMessageTimestampDifferenceMaxMs"},
			_jsii_.MemberMethod{JsiiMethod: "resetMessageTimestampType", GoMethod: "ResetMessageTimestampType"},
			_jsii_.MemberMethod{JsiiMethod: "resetMinCleanableDirtyRatio", GoMethod: "ResetMinCleanableDirtyRatio"},
			_jsii_.MemberMethod{JsiiMethod: "resetMinCompactionLagMs", GoMethod: "ResetMinCompactionLagMs"},
			_jsii_.MemberMethod{JsiiMethod: "resetMinInsyncReplicas", GoMethod: "ResetMinInsyncReplicas"},
			_jsii_.MemberMethod{JsiiMethod: "resetPreallocate", GoMethod: "ResetPreallocate"},
			_jsii_.MemberMethod{JsiiMethod: "resetRetentionBytes", GoMethod: "ResetRetentionBytes"},
			_jsii_.MemberMethod{JsiiMethod: "resetRetentionMs", GoMethod: "ResetRetentionMs"},
			_jsii_.MemberMethod{JsiiMethod: "resetSegmentBytes", GoMethod: "ResetSegmentBytes"},
			_jsii_.MemberMethod{JsiiMethod: "resetSegmentIndexBytes", GoMethod: "ResetSegmentIndexBytes"},
			_jsii_.MemberMethod{JsiiMethod: "resetSegmentJitterMs", GoMethod: "ResetSegmentJitterMs"},
			_jsii_.MemberMethod{JsiiMethod: "resetSegmentMs", GoMethod: "ResetSegmentMs"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "retentionBytes", GoGetter: "RetentionBytes"},
			_jsii_.MemberProperty{JsiiProperty: "retentionBytesInput", GoGetter: "RetentionBytesInput"},
			_jsii_.MemberProperty{JsiiProperty: "retentionMs", GoGetter: "RetentionMs"},
			_jsii_.MemberProperty{JsiiProperty: "retentionMsInput", GoGetter: "RetentionMsInput"},
			_jsii_.MemberProperty{JsiiProperty: "segmentBytes", GoGetter: "SegmentBytes"},
			_jsii_.MemberProperty{JsiiProperty: "segmentBytesInput", GoGetter: "SegmentBytesInput"},
			_jsii_.MemberProperty{JsiiProperty: "segmentIndexBytes", GoGetter: "SegmentIndexBytes"},
			_jsii_.MemberProperty{JsiiProperty: "segmentIndexBytesInput", GoGetter: "SegmentIndexBytesInput"},
			_jsii_.MemberProperty{JsiiProperty: "segmentJitterMs", GoGetter: "SegmentJitterMs"},
			_jsii_.MemberProperty{JsiiProperty: "segmentJitterMsInput", GoGetter: "SegmentJitterMsInput"},
			_jsii_.MemberProperty{JsiiProperty: "segmentMs", GoGetter: "SegmentMs"},
			_jsii_.MemberProperty{JsiiProperty: "segmentMsInput", GoGetter: "SegmentMsInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_DatabaseKafkaTopicConfigAOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
