// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package databasepostgresqlconfig

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-digitalocean.databasePostgresqlConfig.DatabasePostgresqlConfig",
		reflect.TypeOf((*DatabasePostgresqlConfig)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumAnalyzeScaleFactor", GoGetter: "AutovacuumAnalyzeScaleFactor"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumAnalyzeScaleFactorInput", GoGetter: "AutovacuumAnalyzeScaleFactorInput"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumAnalyzeThreshold", GoGetter: "AutovacuumAnalyzeThreshold"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumAnalyzeThresholdInput", GoGetter: "AutovacuumAnalyzeThresholdInput"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumFreezeMaxAge", GoGetter: "AutovacuumFreezeMaxAge"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumFreezeMaxAgeInput", GoGetter: "AutovacuumFreezeMaxAgeInput"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumMaxWorkers", GoGetter: "AutovacuumMaxWorkers"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumMaxWorkersInput", GoGetter: "AutovacuumMaxWorkersInput"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumNaptime", GoGetter: "AutovacuumNaptime"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumNaptimeInput", GoGetter: "AutovacuumNaptimeInput"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumVacuumCostDelay", GoGetter: "AutovacuumVacuumCostDelay"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumVacuumCostDelayInput", GoGetter: "AutovacuumVacuumCostDelayInput"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumVacuumCostLimit", GoGetter: "AutovacuumVacuumCostLimit"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumVacuumCostLimitInput", GoGetter: "AutovacuumVacuumCostLimitInput"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumVacuumScaleFactor", GoGetter: "AutovacuumVacuumScaleFactor"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumVacuumScaleFactorInput", GoGetter: "AutovacuumVacuumScaleFactorInput"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumVacuumThreshold", GoGetter: "AutovacuumVacuumThreshold"},
			_jsii_.MemberProperty{JsiiProperty: "autovacuumVacuumThresholdInput", GoGetter: "AutovacuumVacuumThresholdInput"},
			_jsii_.MemberProperty{JsiiProperty: "backupHour", GoGetter: "BackupHour"},
			_jsii_.MemberProperty{JsiiProperty: "backupHourInput", GoGetter: "BackupHourInput"},
			_jsii_.MemberProperty{JsiiProperty: "backupMinute", GoGetter: "BackupMinute"},
			_jsii_.MemberProperty{JsiiProperty: "backupMinuteInput", GoGetter: "BackupMinuteInput"},
			_jsii_.MemberProperty{JsiiProperty: "bgwriterDelay", GoGetter: "BgwriterDelay"},
			_jsii_.MemberProperty{JsiiProperty: "bgwriterDelayInput", GoGetter: "BgwriterDelayInput"},
			_jsii_.MemberProperty{JsiiProperty: "bgwriterFlushAfter", GoGetter: "BgwriterFlushAfter"},
			_jsii_.MemberProperty{JsiiProperty: "bgwriterFlushAfterInput", GoGetter: "BgwriterFlushAfterInput"},
			_jsii_.MemberProperty{JsiiProperty: "bgwriterLruMaxpages", GoGetter: "BgwriterLruMaxpages"},
			_jsii_.MemberProperty{JsiiProperty: "bgwriterLruMaxpagesInput", GoGetter: "BgwriterLruMaxpagesInput"},
			_jsii_.MemberProperty{JsiiProperty: "bgwriterLruMultiplier", GoGetter: "BgwriterLruMultiplier"},
			_jsii_.MemberProperty{JsiiProperty: "bgwriterLruMultiplierInput", GoGetter: "BgwriterLruMultiplierInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "clusterId", GoGetter: "ClusterId"},
			_jsii_.MemberProperty{JsiiProperty: "clusterIdInput", GoGetter: "ClusterIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "deadlockTimeout", GoGetter: "DeadlockTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "deadlockTimeoutInput", GoGetter: "DeadlockTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "defaultToastCompression", GoGetter: "DefaultToastCompression"},
			_jsii_.MemberProperty{JsiiProperty: "defaultToastCompressionInput", GoGetter: "DefaultToastCompressionInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberProperty{JsiiProperty: "idleInTransactionSessionTimeout", GoGetter: "IdleInTransactionSessionTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "idleInTransactionSessionTimeoutInput", GoGetter: "IdleInTransactionSessionTimeoutInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "jit", GoGetter: "Jit"},
			_jsii_.MemberProperty{JsiiProperty: "jitInput", GoGetter: "JitInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "logAutovacuumMinDuration", GoGetter: "LogAutovacuumMinDuration"},
			_jsii_.MemberProperty{JsiiProperty: "logAutovacuumMinDurationInput", GoGetter: "LogAutovacuumMinDurationInput"},
			_jsii_.MemberProperty{JsiiProperty: "logErrorVerbosity", GoGetter: "LogErrorVerbosity"},
			_jsii_.MemberProperty{JsiiProperty: "logErrorVerbosityInput", GoGetter: "LogErrorVerbosityInput"},
			_jsii_.MemberProperty{JsiiProperty: "logLinePrefix", GoGetter: "LogLinePrefix"},
			_jsii_.MemberProperty{JsiiProperty: "logLinePrefixInput", GoGetter: "LogLinePrefixInput"},
			_jsii_.MemberProperty{JsiiProperty: "logMinDurationStatement", GoGetter: "LogMinDurationStatement"},
			_jsii_.MemberProperty{JsiiProperty: "logMinDurationStatementInput", GoGetter: "LogMinDurationStatementInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxFilesPerProcess", GoGetter: "MaxFilesPerProcess"},
			_jsii_.MemberProperty{JsiiProperty: "maxFilesPerProcessInput", GoGetter: "MaxFilesPerProcessInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxLocksPerTransaction", GoGetter: "MaxLocksPerTransaction"},
			_jsii_.MemberProperty{JsiiProperty: "maxLocksPerTransactionInput", GoGetter: "MaxLocksPerTransactionInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxLogicalReplicationWorkers", GoGetter: "MaxLogicalReplicationWorkers"},
			_jsii_.MemberProperty{JsiiProperty: "maxLogicalReplicationWorkersInput", GoGetter: "MaxLogicalReplicationWorkersInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxParallelWorkers", GoGetter: "MaxParallelWorkers"},
			_jsii_.MemberProperty{JsiiProperty: "maxParallelWorkersInput", GoGetter: "MaxParallelWorkersInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxParallelWorkersPerGather", GoGetter: "MaxParallelWorkersPerGather"},
			_jsii_.MemberProperty{JsiiProperty: "maxParallelWorkersPerGatherInput", GoGetter: "MaxParallelWorkersPerGatherInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxPredLocksPerTransaction", GoGetter: "MaxPredLocksPerTransaction"},
			_jsii_.MemberProperty{JsiiProperty: "maxPredLocksPerTransactionInput", GoGetter: "MaxPredLocksPerTransactionInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxPreparedTransactions", GoGetter: "MaxPreparedTransactions"},
			_jsii_.MemberProperty{JsiiProperty: "maxPreparedTransactionsInput", GoGetter: "MaxPreparedTransactionsInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxReplicationSlots", GoGetter: "MaxReplicationSlots"},
			_jsii_.MemberProperty{JsiiProperty: "maxReplicationSlotsInput", GoGetter: "MaxReplicationSlotsInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxStackDepth", GoGetter: "MaxStackDepth"},
			_jsii_.MemberProperty{JsiiProperty: "maxStackDepthInput", GoGetter: "MaxStackDepthInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxStandbyArchiveDelay", GoGetter: "MaxStandbyArchiveDelay"},
			_jsii_.MemberProperty{JsiiProperty: "maxStandbyArchiveDelayInput", GoGetter: "MaxStandbyArchiveDelayInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxStandbyStreamingDelay", GoGetter: "MaxStandbyStreamingDelay"},
			_jsii_.MemberProperty{JsiiProperty: "maxStandbyStreamingDelayInput", GoGetter: "MaxStandbyStreamingDelayInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxWalSenders", GoGetter: "MaxWalSenders"},
			_jsii_.MemberProperty{JsiiProperty: "maxWalSendersInput", GoGetter: "MaxWalSendersInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxWorkerProcesses", GoGetter: "MaxWorkerProcesses"},
			_jsii_.MemberProperty{JsiiProperty: "maxWorkerProcessesInput", GoGetter: "MaxWorkerProcessesInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "pgbouncer", GoGetter: "Pgbouncer"},
			_jsii_.MemberProperty{JsiiProperty: "pgbouncerInput", GoGetter: "PgbouncerInput"},
			_jsii_.MemberProperty{JsiiProperty: "pgPartmanBgwInterval", GoGetter: "PgPartmanBgwInterval"},
			_jsii_.MemberProperty{JsiiProperty: "pgPartmanBgwIntervalInput", GoGetter: "PgPartmanBgwIntervalInput"},
			_jsii_.MemberProperty{JsiiProperty: "pgPartmanBgwRole", GoGetter: "PgPartmanBgwRole"},
			_jsii_.MemberProperty{JsiiProperty: "pgPartmanBgwRoleInput", GoGetter: "PgPartmanBgwRoleInput"},
			_jsii_.MemberProperty{JsiiProperty: "pgStatStatementsTrack", GoGetter: "PgStatStatementsTrack"},
			_jsii_.MemberProperty{JsiiProperty: "pgStatStatementsTrackInput", GoGetter: "PgStatStatementsTrackInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putPgbouncer", GoMethod: "PutPgbouncer"},
			_jsii_.MemberMethod{JsiiMethod: "putTimescaledb", GoMethod: "PutTimescaledb"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutovacuumAnalyzeScaleFactor", GoMethod: "ResetAutovacuumAnalyzeScaleFactor"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutovacuumAnalyzeThreshold", GoMethod: "ResetAutovacuumAnalyzeThreshold"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutovacuumFreezeMaxAge", GoMethod: "ResetAutovacuumFreezeMaxAge"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutovacuumMaxWorkers", GoMethod: "ResetAutovacuumMaxWorkers"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutovacuumNaptime", GoMethod: "ResetAutovacuumNaptime"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutovacuumVacuumCostDelay", GoMethod: "ResetAutovacuumVacuumCostDelay"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutovacuumVacuumCostLimit", GoMethod: "ResetAutovacuumVacuumCostLimit"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutovacuumVacuumScaleFactor", GoMethod: "ResetAutovacuumVacuumScaleFactor"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutovacuumVacuumThreshold", GoMethod: "ResetAutovacuumVacuumThreshold"},
			_jsii_.MemberMethod{JsiiMethod: "resetBackupHour", GoMethod: "ResetBackupHour"},
			_jsii_.MemberMethod{JsiiMethod: "resetBackupMinute", GoMethod: "ResetBackupMinute"},
			_jsii_.MemberMethod{JsiiMethod: "resetBgwriterDelay", GoMethod: "ResetBgwriterDelay"},
			_jsii_.MemberMethod{JsiiMethod: "resetBgwriterFlushAfter", GoMethod: "ResetBgwriterFlushAfter"},
			_jsii_.MemberMethod{JsiiMethod: "resetBgwriterLruMaxpages", GoMethod: "ResetBgwriterLruMaxpages"},
			_jsii_.MemberMethod{JsiiMethod: "resetBgwriterLruMultiplier", GoMethod: "ResetBgwriterLruMultiplier"},
			_jsii_.MemberMethod{JsiiMethod: "resetDeadlockTimeout", GoMethod: "ResetDeadlockTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetDefaultToastCompression", GoMethod: "ResetDefaultToastCompression"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetIdleInTransactionSessionTimeout", GoMethod: "ResetIdleInTransactionSessionTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetJit", GoMethod: "ResetJit"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogAutovacuumMinDuration", GoMethod: "ResetLogAutovacuumMinDuration"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogErrorVerbosity", GoMethod: "ResetLogErrorVerbosity"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogLinePrefix", GoMethod: "ResetLogLinePrefix"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogMinDurationStatement", GoMethod: "ResetLogMinDurationStatement"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxFilesPerProcess", GoMethod: "ResetMaxFilesPerProcess"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxLocksPerTransaction", GoMethod: "ResetMaxLocksPerTransaction"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxLogicalReplicationWorkers", GoMethod: "ResetMaxLogicalReplicationWorkers"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxParallelWorkers", GoMethod: "ResetMaxParallelWorkers"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxParallelWorkersPerGather", GoMethod: "ResetMaxParallelWorkersPerGather"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxPredLocksPerTransaction", GoMethod: "ResetMaxPredLocksPerTransaction"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxPreparedTransactions", GoMethod: "ResetMaxPreparedTransactions"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxReplicationSlots", GoMethod: "ResetMaxReplicationSlots"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxStackDepth", GoMethod: "ResetMaxStackDepth"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxStandbyArchiveDelay", GoMethod: "ResetMaxStandbyArchiveDelay"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxStandbyStreamingDelay", GoMethod: "ResetMaxStandbyStreamingDelay"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxWalSenders", GoMethod: "ResetMaxWalSenders"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxWorkerProcesses", GoMethod: "ResetMaxWorkerProcesses"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetPgbouncer", GoMethod: "ResetPgbouncer"},
			_jsii_.MemberMethod{JsiiMethod: "resetPgPartmanBgwInterval", GoMethod: "ResetPgPartmanBgwInterval"},
			_jsii_.MemberMethod{JsiiMethod: "resetPgPartmanBgwRole", GoMethod: "ResetPgPartmanBgwRole"},
			_jsii_.MemberMethod{JsiiMethod: "resetPgStatStatementsTrack", GoMethod: "ResetPgStatStatementsTrack"},
			_jsii_.MemberMethod{JsiiMethod: "resetSharedBuffersPercentage", GoMethod: "ResetSharedBuffersPercentage"},
			_jsii_.MemberMethod{JsiiMethod: "resetTempFileLimit", GoMethod: "ResetTempFileLimit"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimescaledb", GoMethod: "ResetTimescaledb"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimezone", GoMethod: "ResetTimezone"},
			_jsii_.MemberMethod{JsiiMethod: "resetTrackActivityQuerySize", GoMethod: "ResetTrackActivityQuerySize"},
			_jsii_.MemberMethod{JsiiMethod: "resetTrackCommitTimestamp", GoMethod: "ResetTrackCommitTimestamp"},
			_jsii_.MemberMethod{JsiiMethod: "resetTrackFunctions", GoMethod: "ResetTrackFunctions"},
			_jsii_.MemberMethod{JsiiMethod: "resetTrackIoTiming", GoMethod: "ResetTrackIoTiming"},
			_jsii_.MemberMethod{JsiiMethod: "resetWalSenderTimeout", GoMethod: "ResetWalSenderTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetWalWriterDelay", GoMethod: "ResetWalWriterDelay"},
			_jsii_.MemberMethod{JsiiMethod: "resetWorkMem", GoMethod: "ResetWorkMem"},
			_jsii_.MemberProperty{JsiiProperty: "sharedBuffersPercentage", GoGetter: "SharedBuffersPercentage"},
			_jsii_.MemberProperty{JsiiProperty: "sharedBuffersPercentageInput", GoGetter: "SharedBuffersPercentageInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "tempFileLimit", GoGetter: "TempFileLimit"},
			_jsii_.MemberProperty{JsiiProperty: "tempFileLimitInput", GoGetter: "TempFileLimitInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberProperty{JsiiProperty: "timescaledb", GoGetter: "Timescaledb"},
			_jsii_.MemberProperty{JsiiProperty: "timescaledbInput", GoGetter: "TimescaledbInput"},
			_jsii_.MemberProperty{JsiiProperty: "timezone", GoGetter: "Timezone"},
			_jsii_.MemberProperty{JsiiProperty: "timezoneInput", GoGetter: "TimezoneInput"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "trackActivityQuerySize", GoGetter: "TrackActivityQuerySize"},
			_jsii_.MemberProperty{JsiiProperty: "trackActivityQuerySizeInput", GoGetter: "TrackActivityQuerySizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "trackCommitTimestamp", GoGetter: "TrackCommitTimestamp"},
			_jsii_.MemberProperty{JsiiProperty: "trackCommitTimestampInput", GoGetter: "TrackCommitTimestampInput"},
			_jsii_.MemberProperty{JsiiProperty: "trackFunctions", GoGetter: "TrackFunctions"},
			_jsii_.MemberProperty{JsiiProperty: "trackFunctionsInput", GoGetter: "TrackFunctionsInput"},
			_jsii_.MemberProperty{JsiiProperty: "trackIoTiming", GoGetter: "TrackIoTiming"},
			_jsii_.MemberProperty{JsiiProperty: "trackIoTimingInput", GoGetter: "TrackIoTimingInput"},
			_jsii_.MemberProperty{JsiiProperty: "walSenderTimeout", GoGetter: "WalSenderTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "walSenderTimeoutInput", GoGetter: "WalSenderTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "walWriterDelay", GoGetter: "WalWriterDelay"},
			_jsii_.MemberProperty{JsiiProperty: "walWriterDelayInput", GoGetter: "WalWriterDelayInput"},
			_jsii_.MemberProperty{JsiiProperty: "workMem", GoGetter: "WorkMem"},
			_jsii_.MemberProperty{JsiiProperty: "workMemInput", GoGetter: "WorkMemInput"},
		},
		func() interface{} {
			j := jsiiProxy_DatabasePostgresqlConfig{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-digitalocean.databasePostgresqlConfig.DatabasePostgresqlConfigConfig",
		reflect.TypeOf((*DatabasePostgresqlConfigConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-digitalocean.databasePostgresqlConfig.DatabasePostgresqlConfigPgbouncer",
		reflect.TypeOf((*DatabasePostgresqlConfigPgbouncer)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-digitalocean.databasePostgresqlConfig.DatabasePostgresqlConfigPgbouncerList",
		reflect.TypeOf((*DatabasePostgresqlConfigPgbouncerList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "allWithMapKey", GoMethod: "AllWithMapKey"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_DatabasePostgresqlConfigPgbouncerList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-digitalocean.databasePostgresqlConfig.DatabasePostgresqlConfigPgbouncerOutputReference",
		reflect.TypeOf((*DatabasePostgresqlConfigPgbouncerOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "autodbIdleTimeout", GoGetter: "AutodbIdleTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "autodbIdleTimeoutInput", GoGetter: "AutodbIdleTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "autodbMaxDbConnections", GoGetter: "AutodbMaxDbConnections"},
			_jsii_.MemberProperty{JsiiProperty: "autodbMaxDbConnectionsInput", GoGetter: "AutodbMaxDbConnectionsInput"},
			_jsii_.MemberProperty{JsiiProperty: "autodbPoolMode", GoGetter: "AutodbPoolMode"},
			_jsii_.MemberProperty{JsiiProperty: "autodbPoolModeInput", GoGetter: "AutodbPoolModeInput"},
			_jsii_.MemberProperty{JsiiProperty: "autodbPoolSize", GoGetter: "AutodbPoolSize"},
			_jsii_.MemberProperty{JsiiProperty: "autodbPoolSizeInput", GoGetter: "AutodbPoolSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "ignoreStartupParameters", GoGetter: "IgnoreStartupParameters"},
			_jsii_.MemberProperty{JsiiProperty: "ignoreStartupParametersInput", GoGetter: "IgnoreStartupParametersInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "minPoolSize", GoGetter: "MinPoolSize"},
			_jsii_.MemberProperty{JsiiProperty: "minPoolSizeInput", GoGetter: "MinPoolSizeInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutodbIdleTimeout", GoMethod: "ResetAutodbIdleTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutodbMaxDbConnections", GoMethod: "ResetAutodbMaxDbConnections"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutodbPoolMode", GoMethod: "ResetAutodbPoolMode"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutodbPoolSize", GoMethod: "ResetAutodbPoolSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetIgnoreStartupParameters", GoMethod: "ResetIgnoreStartupParameters"},
			_jsii_.MemberMethod{JsiiMethod: "resetMinPoolSize", GoMethod: "ResetMinPoolSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetServerIdleTimeout", GoMethod: "ResetServerIdleTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetServerLifetime", GoMethod: "ResetServerLifetime"},
			_jsii_.MemberMethod{JsiiMethod: "resetServerResetQueryAlways", GoMethod: "ResetServerResetQueryAlways"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "serverIdleTimeout", GoGetter: "ServerIdleTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "serverIdleTimeoutInput", GoGetter: "ServerIdleTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "serverLifetime", GoGetter: "ServerLifetime"},
			_jsii_.MemberProperty{JsiiProperty: "serverLifetimeInput", GoGetter: "ServerLifetimeInput"},
			_jsii_.MemberProperty{JsiiProperty: "serverResetQueryAlways", GoGetter: "ServerResetQueryAlways"},
			_jsii_.MemberProperty{JsiiProperty: "serverResetQueryAlwaysInput", GoGetter: "ServerResetQueryAlwaysInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_DatabasePostgresqlConfigPgbouncerOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-digitalocean.databasePostgresqlConfig.DatabasePostgresqlConfigTimescaledb",
		reflect.TypeOf((*DatabasePostgresqlConfigTimescaledb)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-digitalocean.databasePostgresqlConfig.DatabasePostgresqlConfigTimescaledbList",
		reflect.TypeOf((*DatabasePostgresqlConfigTimescaledbList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "allWithMapKey", GoMethod: "AllWithMapKey"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_DatabasePostgresqlConfigTimescaledbList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-digitalocean.databasePostgresqlConfig.DatabasePostgresqlConfigTimescaledbOutputReference",
		reflect.TypeOf((*DatabasePostgresqlConfigTimescaledbOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimescaledb", GoMethod: "ResetTimescaledb"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberProperty{JsiiProperty: "timescaledb", GoGetter: "Timescaledb"},
			_jsii_.MemberProperty{JsiiProperty: "timescaledbInput", GoGetter: "TimescaledbInput"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_DatabasePostgresqlConfigTimescaledbOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
