// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package databaseopensearchconfig

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-digitalocean.databaseOpensearchConfig.DatabaseOpensearchConfig",
		reflect.TypeOf((*DatabaseOpensearchConfig)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "actionAutoCreateIndexEnabled", GoGetter: "ActionAutoCreateIndexEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "actionAutoCreateIndexEnabledInput", GoGetter: "ActionAutoCreateIndexEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "actionDestructiveRequiresName", GoGetter: "ActionDestructiveRequiresName"},
			_jsii_.MemberProperty{JsiiProperty: "actionDestructiveRequiresNameInput", GoGetter: "ActionDestructiveRequiresNameInput"},
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "clusterId", GoGetter: "ClusterId"},
			_jsii_.MemberProperty{JsiiProperty: "clusterIdInput", GoGetter: "ClusterIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "clusterMaxShardsPerNode", GoGetter: "ClusterMaxShardsPerNode"},
			_jsii_.MemberProperty{JsiiProperty: "clusterMaxShardsPerNodeInput", GoGetter: "ClusterMaxShardsPerNodeInput"},
			_jsii_.MemberProperty{JsiiProperty: "clusterRoutingAllocationNodeConcurrentRecoveries", GoGetter: "ClusterRoutingAllocationNodeConcurrentRecoveries"},
			_jsii_.MemberProperty{JsiiProperty: "clusterRoutingAllocationNodeConcurrentRecoveriesInput", GoGetter: "ClusterRoutingAllocationNodeConcurrentRecoveriesInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "enableSecurityAudit", GoGetter: "EnableSecurityAudit"},
			_jsii_.MemberProperty{JsiiProperty: "enableSecurityAuditInput", GoGetter: "EnableSecurityAuditInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "httpMaxContentLengthBytes", GoGetter: "HttpMaxContentLengthBytes"},
			_jsii_.MemberProperty{JsiiProperty: "httpMaxContentLengthBytesInput", GoGetter: "HttpMaxContentLengthBytesInput"},
			_jsii_.MemberProperty{JsiiProperty: "httpMaxHeaderSizeBytes", GoGetter: "HttpMaxHeaderSizeBytes"},
			_jsii_.MemberProperty{JsiiProperty: "httpMaxHeaderSizeBytesInput", GoGetter: "HttpMaxHeaderSizeBytesInput"},
			_jsii_.MemberProperty{JsiiProperty: "httpMaxInitialLineLengthBytes", GoGetter: "HttpMaxInitialLineLengthBytes"},
			_jsii_.MemberProperty{JsiiProperty: "httpMaxInitialLineLengthBytesInput", GoGetter: "HttpMaxInitialLineLengthBytesInput"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberProperty{JsiiProperty: "indicesFielddataCacheSizePercentage", GoGetter: "IndicesFielddataCacheSizePercentage"},
			_jsii_.MemberProperty{JsiiProperty: "indicesFielddataCacheSizePercentageInput", GoGetter: "IndicesFielddataCacheSizePercentageInput"},
			_jsii_.MemberProperty{JsiiProperty: "indicesMemoryIndexBufferSizePercentage", GoGetter: "IndicesMemoryIndexBufferSizePercentage"},
			_jsii_.MemberProperty{JsiiProperty: "indicesMemoryIndexBufferSizePercentageInput", GoGetter: "IndicesMemoryIndexBufferSizePercentageInput"},
			_jsii_.MemberProperty{JsiiProperty: "indicesMemoryMaxIndexBufferSizeMb", GoGetter: "IndicesMemoryMaxIndexBufferSizeMb"},
			_jsii_.MemberProperty{JsiiProperty: "indicesMemoryMaxIndexBufferSizeMbInput", GoGetter: "IndicesMemoryMaxIndexBufferSizeMbInput"},
			_jsii_.MemberProperty{JsiiProperty: "indicesMemoryMinIndexBufferSizeMb", GoGetter: "IndicesMemoryMinIndexBufferSizeMb"},
			_jsii_.MemberProperty{JsiiProperty: "indicesMemoryMinIndexBufferSizeMbInput", GoGetter: "IndicesMemoryMinIndexBufferSizeMbInput"},
			_jsii_.MemberProperty{JsiiProperty: "indicesQueriesCacheSizePercentage", GoGetter: "IndicesQueriesCacheSizePercentage"},
			_jsii_.MemberProperty{JsiiProperty: "indicesQueriesCacheSizePercentageInput", GoGetter: "IndicesQueriesCacheSizePercentageInput"},
			_jsii_.MemberProperty{JsiiProperty: "indicesQueryBoolMaxClauseCount", GoGetter: "IndicesQueryBoolMaxClauseCount"},
			_jsii_.MemberProperty{JsiiProperty: "indicesQueryBoolMaxClauseCountInput", GoGetter: "IndicesQueryBoolMaxClauseCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "indicesRecoveryMaxConcurrentFileChunks", GoGetter: "IndicesRecoveryMaxConcurrentFileChunks"},
			_jsii_.MemberProperty{JsiiProperty: "indicesRecoveryMaxConcurrentFileChunksInput", GoGetter: "IndicesRecoveryMaxConcurrentFileChunksInput"},
			_jsii_.MemberProperty{JsiiProperty: "indicesRecoveryMaxMbPerSec", GoGetter: "IndicesRecoveryMaxMbPerSec"},
			_jsii_.MemberProperty{JsiiProperty: "indicesRecoveryMaxMbPerSecInput", GoGetter: "IndicesRecoveryMaxMbPerSecInput"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "ismEnabled", GoGetter: "IsmEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "ismEnabledInput", GoGetter: "IsmEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "ismHistoryEnabled", GoGetter: "IsmHistoryEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "ismHistoryEnabledInput", GoGetter: "IsmHistoryEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "ismHistoryMaxAgeHours", GoGetter: "IsmHistoryMaxAgeHours"},
			_jsii_.MemberProperty{JsiiProperty: "ismHistoryMaxAgeHoursInput", GoGetter: "IsmHistoryMaxAgeHoursInput"},
			_jsii_.MemberProperty{JsiiProperty: "ismHistoryMaxDocs", GoGetter: "IsmHistoryMaxDocs"},
			_jsii_.MemberProperty{JsiiProperty: "ismHistoryMaxDocsInput", GoGetter: "IsmHistoryMaxDocsInput"},
			_jsii_.MemberProperty{JsiiProperty: "ismHistoryRolloverCheckPeriodHours", GoGetter: "IsmHistoryRolloverCheckPeriodHours"},
			_jsii_.MemberProperty{JsiiProperty: "ismHistoryRolloverCheckPeriodHoursInput", GoGetter: "IsmHistoryRolloverCheckPeriodHoursInput"},
			_jsii_.MemberProperty{JsiiProperty: "ismHistoryRolloverRetentionPeriodDays", GoGetter: "IsmHistoryRolloverRetentionPeriodDays"},
			_jsii_.MemberProperty{JsiiProperty: "ismHistoryRolloverRetentionPeriodDaysInput", GoGetter: "IsmHistoryRolloverRetentionPeriodDaysInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "overrideMainResponseVersion", GoGetter: "OverrideMainResponseVersion"},
			_jsii_.MemberProperty{JsiiProperty: "overrideMainResponseVersionInput", GoGetter: "OverrideMainResponseVersionInput"},
			_jsii_.MemberProperty{JsiiProperty: "pluginsAlertingFilterByBackendRolesEnabled", GoGetter: "PluginsAlertingFilterByBackendRolesEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "pluginsAlertingFilterByBackendRolesEnabledInput", GoGetter: "PluginsAlertingFilterByBackendRolesEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "reindexRemoteWhitelist", GoGetter: "ReindexRemoteWhitelist"},
			_jsii_.MemberProperty{JsiiProperty: "reindexRemoteWhitelistInput", GoGetter: "ReindexRemoteWhitelistInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetActionAutoCreateIndexEnabled", GoMethod: "ResetActionAutoCreateIndexEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetActionDestructiveRequiresName", GoMethod: "ResetActionDestructiveRequiresName"},
			_jsii_.MemberMethod{JsiiMethod: "resetClusterMaxShardsPerNode", GoMethod: "ResetClusterMaxShardsPerNode"},
			_jsii_.MemberMethod{JsiiMethod: "resetClusterRoutingAllocationNodeConcurrentRecoveries", GoMethod: "ResetClusterRoutingAllocationNodeConcurrentRecoveries"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableSecurityAudit", GoMethod: "ResetEnableSecurityAudit"},
			_jsii_.MemberMethod{JsiiMethod: "resetHttpMaxContentLengthBytes", GoMethod: "ResetHttpMaxContentLengthBytes"},
			_jsii_.MemberMethod{JsiiMethod: "resetHttpMaxHeaderSizeBytes", GoMethod: "ResetHttpMaxHeaderSizeBytes"},
			_jsii_.MemberMethod{JsiiMethod: "resetHttpMaxInitialLineLengthBytes", GoMethod: "ResetHttpMaxInitialLineLengthBytes"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetIndicesFielddataCacheSizePercentage", GoMethod: "ResetIndicesFielddataCacheSizePercentage"},
			_jsii_.MemberMethod{JsiiMethod: "resetIndicesMemoryIndexBufferSizePercentage", GoMethod: "ResetIndicesMemoryIndexBufferSizePercentage"},
			_jsii_.MemberMethod{JsiiMethod: "resetIndicesMemoryMaxIndexBufferSizeMb", GoMethod: "ResetIndicesMemoryMaxIndexBufferSizeMb"},
			_jsii_.MemberMethod{JsiiMethod: "resetIndicesMemoryMinIndexBufferSizeMb", GoMethod: "ResetIndicesMemoryMinIndexBufferSizeMb"},
			_jsii_.MemberMethod{JsiiMethod: "resetIndicesQueriesCacheSizePercentage", GoMethod: "ResetIndicesQueriesCacheSizePercentage"},
			_jsii_.MemberMethod{JsiiMethod: "resetIndicesQueryBoolMaxClauseCount", GoMethod: "ResetIndicesQueryBoolMaxClauseCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetIndicesRecoveryMaxConcurrentFileChunks", GoMethod: "ResetIndicesRecoveryMaxConcurrentFileChunks"},
			_jsii_.MemberMethod{JsiiMethod: "resetIndicesRecoveryMaxMbPerSec", GoMethod: "ResetIndicesRecoveryMaxMbPerSec"},
			_jsii_.MemberMethod{JsiiMethod: "resetIsmEnabled", GoMethod: "ResetIsmEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetIsmHistoryEnabled", GoMethod: "ResetIsmHistoryEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetIsmHistoryMaxAgeHours", GoMethod: "ResetIsmHistoryMaxAgeHours"},
			_jsii_.MemberMethod{JsiiMethod: "resetIsmHistoryMaxDocs", GoMethod: "ResetIsmHistoryMaxDocs"},
			_jsii_.MemberMethod{JsiiMethod: "resetIsmHistoryRolloverCheckPeriodHours", GoMethod: "ResetIsmHistoryRolloverCheckPeriodHours"},
			_jsii_.MemberMethod{JsiiMethod: "resetIsmHistoryRolloverRetentionPeriodDays", GoMethod: "ResetIsmHistoryRolloverRetentionPeriodDays"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideMainResponseVersion", GoMethod: "ResetOverrideMainResponseVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetPluginsAlertingFilterByBackendRolesEnabled", GoMethod: "ResetPluginsAlertingFilterByBackendRolesEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetReindexRemoteWhitelist", GoMethod: "ResetReindexRemoteWhitelist"},
			_jsii_.MemberMethod{JsiiMethod: "resetScriptMaxCompilationsRate", GoMethod: "ResetScriptMaxCompilationsRate"},
			_jsii_.MemberMethod{JsiiMethod: "resetSearchMaxBuckets", GoMethod: "ResetSearchMaxBuckets"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolAnalyzeQueueSize", GoMethod: "ResetThreadPoolAnalyzeQueueSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolAnalyzeSize", GoMethod: "ResetThreadPoolAnalyzeSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolForceMergeSize", GoMethod: "ResetThreadPoolForceMergeSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolGetQueueSize", GoMethod: "ResetThreadPoolGetQueueSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolGetSize", GoMethod: "ResetThreadPoolGetSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolSearchQueueSize", GoMethod: "ResetThreadPoolSearchQueueSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolSearchSize", GoMethod: "ResetThreadPoolSearchSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolSearchThrottledQueueSize", GoMethod: "ResetThreadPoolSearchThrottledQueueSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolSearchThrottledSize", GoMethod: "ResetThreadPoolSearchThrottledSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolWriteQueueSize", GoMethod: "ResetThreadPoolWriteQueueSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetThreadPoolWriteSize", GoMethod: "ResetThreadPoolWriteSize"},
			_jsii_.MemberProperty{JsiiProperty: "scriptMaxCompilationsRate", GoGetter: "ScriptMaxCompilationsRate"},
			_jsii_.MemberProperty{JsiiProperty: "scriptMaxCompilationsRateInput", GoGetter: "ScriptMaxCompilationsRateInput"},
			_jsii_.MemberProperty{JsiiProperty: "searchMaxBuckets", GoGetter: "SearchMaxBuckets"},
			_jsii_.MemberProperty{JsiiProperty: "searchMaxBucketsInput", GoGetter: "SearchMaxBucketsInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolAnalyzeQueueSize", GoGetter: "ThreadPoolAnalyzeQueueSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolAnalyzeQueueSizeInput", GoGetter: "ThreadPoolAnalyzeQueueSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolAnalyzeSize", GoGetter: "ThreadPoolAnalyzeSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolAnalyzeSizeInput", GoGetter: "ThreadPoolAnalyzeSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolForceMergeSize", GoGetter: "ThreadPoolForceMergeSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolForceMergeSizeInput", GoGetter: "ThreadPoolForceMergeSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolGetQueueSize", GoGetter: "ThreadPoolGetQueueSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolGetQueueSizeInput", GoGetter: "ThreadPoolGetQueueSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolGetSize", GoGetter: "ThreadPoolGetSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolGetSizeInput", GoGetter: "ThreadPoolGetSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolSearchQueueSize", GoGetter: "ThreadPoolSearchQueueSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolSearchQueueSizeInput", GoGetter: "ThreadPoolSearchQueueSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolSearchSize", GoGetter: "ThreadPoolSearchSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolSearchSizeInput", GoGetter: "ThreadPoolSearchSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolSearchThrottledQueueSize", GoGetter: "ThreadPoolSearchThrottledQueueSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolSearchThrottledQueueSizeInput", GoGetter: "ThreadPoolSearchThrottledQueueSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolSearchThrottledSize", GoGetter: "ThreadPoolSearchThrottledSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolSearchThrottledSizeInput", GoGetter: "ThreadPoolSearchThrottledSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolWriteQueueSize", GoGetter: "ThreadPoolWriteQueueSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolWriteQueueSizeInput", GoGetter: "ThreadPoolWriteQueueSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolWriteSize", GoGetter: "ThreadPoolWriteSize"},
			_jsii_.MemberProperty{JsiiProperty: "threadPoolWriteSizeInput", GoGetter: "ThreadPoolWriteSizeInput"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
		},
		func() interface{} {
			j := jsiiProxy_DatabaseOpensearchConfig{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-digitalocean.databaseOpensearchConfig.DatabaseOpensearchConfigConfig",
		reflect.TypeOf((*DatabaseOpensearchConfigConfig)(nil)).Elem(),
	)
}
