// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package databasemysqlconfig

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-digitalocean.databaseMysqlConfig.DatabaseMysqlConfig",
		reflect.TypeOf((*DatabaseMysqlConfig)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "backupHour", GoGetter: "BackupHour"},
			_jsii_.MemberProperty{JsiiProperty: "backupHourInput", GoGetter: "BackupHourInput"},
			_jsii_.MemberProperty{JsiiProperty: "backupMinute", GoGetter: "BackupMinute"},
			_jsii_.MemberProperty{JsiiProperty: "backupMinuteInput", GoGetter: "BackupMinuteInput"},
			_jsii_.MemberProperty{JsiiProperty: "binlogRetentionPeriod", GoGetter: "BinlogRetentionPeriod"},
			_jsii_.MemberProperty{JsiiProperty: "binlogRetentionPeriodInput", GoGetter: "BinlogRetentionPeriodInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "clusterId", GoGetter: "ClusterId"},
			_jsii_.MemberProperty{JsiiProperty: "clusterIdInput", GoGetter: "ClusterIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "connectTimeout", GoGetter: "ConnectTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "connectTimeoutInput", GoGetter: "ConnectTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "defaultTimeZone", GoGetter: "DefaultTimeZone"},
			_jsii_.MemberProperty{JsiiProperty: "defaultTimeZoneInput", GoGetter: "DefaultTimeZoneInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "groupConcatMaxLen", GoGetter: "GroupConcatMaxLen"},
			_jsii_.MemberProperty{JsiiProperty: "groupConcatMaxLenInput", GoGetter: "GroupConcatMaxLenInput"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberProperty{JsiiProperty: "informationSchemaStatsExpiry", GoGetter: "InformationSchemaStatsExpiry"},
			_jsii_.MemberProperty{JsiiProperty: "informationSchemaStatsExpiryInput", GoGetter: "InformationSchemaStatsExpiryInput"},
			_jsii_.MemberProperty{JsiiProperty: "innodbFtMinTokenSize", GoGetter: "InnodbFtMinTokenSize"},
			_jsii_.MemberProperty{JsiiProperty: "innodbFtMinTokenSizeInput", GoGetter: "InnodbFtMinTokenSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "innodbFtServerStopwordTable", GoGetter: "InnodbFtServerStopwordTable"},
			_jsii_.MemberProperty{JsiiProperty: "innodbFtServerStopwordTableInput", GoGetter: "InnodbFtServerStopwordTableInput"},
			_jsii_.MemberProperty{JsiiProperty: "innodbLockWaitTimeout", GoGetter: "InnodbLockWaitTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "innodbLockWaitTimeoutInput", GoGetter: "InnodbLockWaitTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "innodbLogBufferSize", GoGetter: "InnodbLogBufferSize"},
			_jsii_.MemberProperty{JsiiProperty: "innodbLogBufferSizeInput", GoGetter: "InnodbLogBufferSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "innodbOnlineAlterLogMaxSize", GoGetter: "InnodbOnlineAlterLogMaxSize"},
			_jsii_.MemberProperty{JsiiProperty: "innodbOnlineAlterLogMaxSizeInput", GoGetter: "InnodbOnlineAlterLogMaxSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "innodbPrintAllDeadlocks", GoGetter: "InnodbPrintAllDeadlocks"},
			_jsii_.MemberProperty{JsiiProperty: "innodbPrintAllDeadlocksInput", GoGetter: "InnodbPrintAllDeadlocksInput"},
			_jsii_.MemberProperty{JsiiProperty: "innodbRollbackOnTimeout", GoGetter: "InnodbRollbackOnTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "innodbRollbackOnTimeoutInput", GoGetter: "InnodbRollbackOnTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "interactiveTimeout", GoGetter: "InteractiveTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "interactiveTimeoutInput", GoGetter: "InteractiveTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalTmpMemStorageEngine", GoGetter: "InternalTmpMemStorageEngine"},
			_jsii_.MemberProperty{JsiiProperty: "internalTmpMemStorageEngineInput", GoGetter: "InternalTmpMemStorageEngineInput"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "longQueryTime", GoGetter: "LongQueryTime"},
			_jsii_.MemberProperty{JsiiProperty: "longQueryTimeInput", GoGetter: "LongQueryTimeInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxAllowedPacket", GoGetter: "MaxAllowedPacket"},
			_jsii_.MemberProperty{JsiiProperty: "maxAllowedPacketInput", GoGetter: "MaxAllowedPacketInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxHeapTableSize", GoGetter: "MaxHeapTableSize"},
			_jsii_.MemberProperty{JsiiProperty: "maxHeapTableSizeInput", GoGetter: "MaxHeapTableSizeInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "netReadTimeout", GoGetter: "NetReadTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "netReadTimeoutInput", GoGetter: "NetReadTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "netWriteTimeout", GoGetter: "NetWriteTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "netWriteTimeoutInput", GoGetter: "NetWriteTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetBackupHour", GoMethod: "ResetBackupHour"},
			_jsii_.MemberMethod{JsiiMethod: "resetBackupMinute", GoMethod: "ResetBackupMinute"},
			_jsii_.MemberMethod{JsiiMethod: "resetBinlogRetentionPeriod", GoMethod: "ResetBinlogRetentionPeriod"},
			_jsii_.MemberMethod{JsiiMethod: "resetConnectTimeout", GoMethod: "ResetConnectTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetDefaultTimeZone", GoMethod: "ResetDefaultTimeZone"},
			_jsii_.MemberMethod{JsiiMethod: "resetGroupConcatMaxLen", GoMethod: "ResetGroupConcatMaxLen"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetInformationSchemaStatsExpiry", GoMethod: "ResetInformationSchemaStatsExpiry"},
			_jsii_.MemberMethod{JsiiMethod: "resetInnodbFtMinTokenSize", GoMethod: "ResetInnodbFtMinTokenSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetInnodbFtServerStopwordTable", GoMethod: "ResetInnodbFtServerStopwordTable"},
			_jsii_.MemberMethod{JsiiMethod: "resetInnodbLockWaitTimeout", GoMethod: "ResetInnodbLockWaitTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetInnodbLogBufferSize", GoMethod: "ResetInnodbLogBufferSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetInnodbOnlineAlterLogMaxSize", GoMethod: "ResetInnodbOnlineAlterLogMaxSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetInnodbPrintAllDeadlocks", GoMethod: "ResetInnodbPrintAllDeadlocks"},
			_jsii_.MemberMethod{JsiiMethod: "resetInnodbRollbackOnTimeout", GoMethod: "ResetInnodbRollbackOnTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetInteractiveTimeout", GoMethod: "ResetInteractiveTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetInternalTmpMemStorageEngine", GoMethod: "ResetInternalTmpMemStorageEngine"},
			_jsii_.MemberMethod{JsiiMethod: "resetLongQueryTime", GoMethod: "ResetLongQueryTime"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxAllowedPacket", GoMethod: "ResetMaxAllowedPacket"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxHeapTableSize", GoMethod: "ResetMaxHeapTableSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetReadTimeout", GoMethod: "ResetNetReadTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetWriteTimeout", GoMethod: "ResetNetWriteTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetSlowQueryLog", GoMethod: "ResetSlowQueryLog"},
			_jsii_.MemberMethod{JsiiMethod: "resetSortBufferSize", GoMethod: "ResetSortBufferSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetSqlMode", GoMethod: "ResetSqlMode"},
			_jsii_.MemberMethod{JsiiMethod: "resetSqlRequirePrimaryKey", GoMethod: "ResetSqlRequirePrimaryKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetTmpTableSize", GoMethod: "ResetTmpTableSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetWaitTimeout", GoMethod: "ResetWaitTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "slowQueryLog", GoGetter: "SlowQueryLog"},
			_jsii_.MemberProperty{JsiiProperty: "slowQueryLogInput", GoGetter: "SlowQueryLogInput"},
			_jsii_.MemberProperty{JsiiProperty: "sortBufferSize", GoGetter: "SortBufferSize"},
			_jsii_.MemberProperty{JsiiProperty: "sortBufferSizeInput", GoGetter: "SortBufferSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "sqlMode", GoGetter: "SqlMode"},
			_jsii_.MemberProperty{JsiiProperty: "sqlModeInput", GoGetter: "SqlModeInput"},
			_jsii_.MemberProperty{JsiiProperty: "sqlRequirePrimaryKey", GoGetter: "SqlRequirePrimaryKey"},
			_jsii_.MemberProperty{JsiiProperty: "sqlRequirePrimaryKeyInput", GoGetter: "SqlRequirePrimaryKeyInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberProperty{JsiiProperty: "tmpTableSize", GoGetter: "TmpTableSize"},
			_jsii_.MemberProperty{JsiiProperty: "tmpTableSizeInput", GoGetter: "TmpTableSizeInput"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "waitTimeout", GoGetter: "WaitTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "waitTimeoutInput", GoGetter: "WaitTimeoutInput"},
		},
		func() interface{} {
			j := jsiiProxy_DatabaseMysqlConfig{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-digitalocean.databaseMysqlConfig.DatabaseMysqlConfigConfig",
		reflect.TypeOf((*DatabaseMysqlConfigConfig)(nil)).Elem(),
	)
}
